### ISSUE TITLE
Build script improvements

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#117] opened 2017-11-30 09:19 UTC
I'd like the build script to also report any Bikeshed WARNING and LINK ERROR messages, possibly as fatal. Otherwise we risk introducing subtle issues and letting it all get worse over time. https://github.com/whatwg/fetch/issues/639 is a good example of that happening. Maybe some standards will always have WARNING or LINK ERROR messages, but it seems to me we should not tolerate them. (I actually thought this was fixed for Encoding, but it seems to still happen.)

And in general it should do better with error handling. For FATAL ERROR messages you currently don't see anything and have to run Bikeshed again yourself.

Instead if upon failure we first run `curl https://api.csswg.org/bikeshed/ -f -F file=@fetch.bs -F output=err -F md-Text-Macro="SNAPSHOT-LINK LOCAL COPY"` or some such or store the errors from the initial run directly somehow and then fail the build we'd at least have something to work with.

**Comment by domenic** [comment] 2017-12-13 18:13
This is basically a dupe of https://github.com/whatwg/meta/issues/24; not sure which to close.

**Comment by annevk** [comment] 2017-12-13 19:37
We can have them both until it's fixed. Both are a natural place to search for this issue.

**Comment by annevk** [comment] 2017-12-21 07:00
Another thing: @foolip and have noticed connection issues now and then. I just got hit by "Failed to connect to api.csswg.org port 443: Connection timed out" and we've got the same error for resources.whatwg.org. We could use https://docs.travis-ci.com/user/common-build-problems/#Timeouts-installing-dependencies to make Travis try again once or twice to not have to hit retry ourselves.

**Comment by annevk** [comment] 2018-01-05 08:11
The current situation is really bad. I've basically no idea what's going with Infra at the moment:
```
$ curl --remote-name --fail https://resources.whatwg.org/build/deploy.sh && bash ./deploy.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4546  100  4546    0     0  21753      0 --:--:-- --:--:-- --:--:-- 21855
Commit = af5f4d000d4568fd060b7ff9a450c900a711e773
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 49857    0     0  100 49857      0  42841  0:00:01  0:00:01 --:--:-- 42869
curl: (22) The requested URL returned error: 500 Internal Server Error
The command "curl --remote-name --fail https://resources.whatwg.org/build/deploy.sh && bash ./deploy.sh" exited with 22.
```
Which curl failed here?

**Comment by annevk** [comment] 2018-01-05 10:42
I created #159 which will help, but the main thing that needs looking into is the curl stuff.

**Comment by annevk** [comment] 2018-01-05 11:03
So basically to improve the Bikeshed output we should also run `curl https://api.csswg.org/bikeshed/ -F file=@Overview.bs -F output=err` and maybe run that first. That way we have any warnings and such logged. We could even make it fail on any of those warnings. That seems best?

**Comment by annevk** [comment] 2018-01-05 11:15
(What would be really nice is to send selective output from Travis back to the relevant GitHub PR so you don't have to scroll through a mostly useless log to get the information you need.)

**Comment by domenic** [comment] 2018-01-05 15:16
A number of specs still have warnings, so we might need to be two-stage about it, first outputting errors then failing on warnings.

**Comment by annevk** [comment] 2018-01-08 09:03
Another thing, to deal with the timeout we occasionally hit for the curl requests, we could specify `--retry 2` or some such. This will retry the request when there's a timeout or 5xx response.

**Comment by annevk** [comment] 2018-01-09 14:45
Observed timing out: resources.whatwg.org, api.csswg.org.
Connection problems observed: ^ and sideshowbarker.net (retry would not be effective to solve this one though).

**Comment by annevk** [comment] 2018-01-09 14:47
As for commenting back to the GitHub PR: https://damien.pobel.fr/post/github-api-from-travisci/ can help with that. That seems like a nice thing to try to tackle before we make warnings (and lint errors) fatal. It does seem to require a GitHub token for each repository, so potentially a lot of additional configuration.

**Comment by domenic** [comment] 2018-01-09 16:24
I personally don't like bot comments clogging up GitHub; if the build failed, there's already a nice red X you can click to see the details on the build failure. Pull request comments should be for discussion by humans.

**Comment by annevk** [comment] 2018-01-09 17:38
I mainly don't like waiting on Travis CI to load and scanning through the sometimes rather large logs. But maybe now I've improved the logs it's not so much of a burden.

My suggestion would be to add --retry 2 to our curl calls and then consider this issue closed.

Once linting is there we can do a follow-up on making lint/warnings fatal.

Sounds good?

**Comment by domenic** [comment] 2018-01-09 17:41
SGTM

**Closed** 2018-01-10 18:18 UTC
