### ISSUE TITLE
convert-policy.py gets some stuff in parentheses wrong

### ISSUE THREAD

**Issue by foolip** [whatwg/whatwg.org#134] opened 2017-12-13 21:36 UTC
Moved from https://github.com/whatwg/sg/issues/45, details there.

**Comment by othermaciej** [comment] 2017-12-15 04:38
My understanding of the issue is that parens after brackets should not be treated as a link if there is an intervening space. Global replace of "] (" to "] (" as a preprocessing step should do it, I think.

**Comment by foolip** [comment] 2017-12-15 08:56
"] (" and "] (" are the same string, typo?

**Comment by annevk** [comment] 2017-12-15 13:05
GitHub has a tendency to remove `\`. I recommend using backticks around strings to be sure.

**Comment by domenic** [comment] 2017-12-21 20:20
Fixed by f716ffa145598093d0567d955fde6c4fc9d3a4d1

**Closed by domenic** 2017-12-21 20:20 UTC
